package com.example.app.ads.helper.purchase.utils

/**
 * @author Akshay Harsoda
 * @since 20 Aug 2024
 */
enum class SubscriptionEventType {
    NONE,
    TIME_LINE_SCREEN_OPEN,
    VIEW_ALL_PLANS_SCREEN_OPEN,
    TIME_LINE_SCREEN_CLOSE,
    VIEW_ALL_PLANS_SCREEN_CLOSE,
    VIEW_MORE_PLANS_CLICK,
    MONTHLY_SUBSCRIBE,
    WEEKLY_SUBSCRIBE,
    YEARLY_SUBSCRIBE,
    LIFE_TIME_PURCHASE,
    MONTHLY_FREE_TRAIL_SUBSCRIBE,
    WEEKLY_FREE_TRAIL_SUBSCRIBE,
    YEARLY_FREE_TRAIL_SUBSCRIBE,
    LIFE_TIME_FREE_TRAIL_PURCHASE,
}